name: Build and Publish Helm Chart

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CHART_NAME: url-generator
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        helm-version: '3.8.0'

    - name: Build Helm Chart
      run: |
        helm package .
        helm repo index . --url https://ghcr.io/${{ github.repository_owner }}/$(basename ${{ github.repository }})

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish Helm Chart
      run: |
        helm push ./${{ env.CHART_NAME }}-0.1.0.tgz oci://ghcr.io/${{ github.repository_owner }}/$(basename ${{ github.repository }})
      env:
        HELM_EXPERIMENTAL_OCI: 1
