name: Build and Publish Helm Chart

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        helm-version: '3.8.0'

    - name: Set chart name
      run: echo "CHART_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV

    - name: Build Helm Chart
      run: |
        helm package ./charts/{{ env.CHART_NAME }}
        helm repo index ./charts --url https://ghcr.io/${{ github.repository_owner }}/$(basename ${{ github.repository }})
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN_GITHUB }}

    - name: Publish Helm Chart
      run: |
        helm push ./charts/{{ env.CHART_NAME }}-0.1.0.tgz oci://ghcr.io/${{ github.repository_owner }}/$(basename ${{ github.repository }})
      env:
        HELM_EXPERIMENTAL_OCI: 1
